item_plot_levels <- function(which_items = c("all",
                                             "SI10_Q1_Q8",
                                             "SI10_Q9",
                                             "SI10_Q10",
                                             "SI10_BOTHER")) {

  which_items <- match.arg(which_items)

  switch(which_items,
         all = list("SI10_Q1_Q8" = c("Every time",
                                     "Most of the time",
                                     "About half the time",
                                     "A few times",
                                     "Never",
                                     "Out-of-range",
                                     "Missing (NA)"),
                    "SI10_Q9" = c("11 or more times a day",
                                  "8-10 times a day",
                                  "4-7 times a day",
                                  "3 or fewer times a day",
                                  "Out-of-range",
                                  "Missing (NA)"),
                    "SI10_Q10" = c("More than 3 times",
                                   "2-3 times",
                                   "1 time",
                                   "none",
                                   "Out-of-range",
                                   "Missing (NA)"),
                    "SI10_BOTHER" = c("Extremely bothered",
                                      "Very bothered",
                                      "Somewhat bothered",
                                      "Not at all bothered",
                                      "Out-of-range",
                                      "Missing (NA)")),
         SI10_Q1_Q8 = c("Every time",
                        "Most of the time",
                        "About half the time",
                        "A few times",
                        "Never",
                        "Out-of-range",
                        "Missing (NA)"),
         SI10_Q9 = c("11 or more times a day",
                     "8-10 times a day",
                     "4-7 times a day",
                     "3 or fewer times a day",
                     "Out-of-range",
                     "Missing (NA)"),
         SI10_Q10 = c("More than 3 times",
                      "2-3 times",
                      "1 time",
                      "none",
                      "Out-of-range",
                      "Missing (NA)"),
         SI10_BOTHER = c("Extremely bothered",
                         "Very bothered",
                         "Somewhat bothered",
                         "Not at all bothered",
                         "Out-of-range",
                         "Missing (NA)"))
}
