item_plot_resp_colors <- function(which_items = c("all",
                                                  "SI10_Q1_Q8",
                                                  "SI10_Q9",
                                                  "SI10_Q10",
                                                  "SI10_BOTHER")) {

  which_items <- match.arg(which_items)

  switch(which_items,
         all = list("SI10_Q1_Q8" = c("#08519c",
                                     "#3182bd",
                                     "#6baed6",
                                     "#bdd7e7",
                                     "#eff3ff",
                                     "#FF0000",
                                     "grey50"),
                    "SI10_Q9" = c("#d94701",
                                  "#fd8d3c",
                                  "#fdbe85",
                                  "#feedde",
                                  "#FF0000",
                                  "grey50"),
                    "SI10_Q10" = c("#238b45",
                                   "#74c476",
                                   "#bae4b3",
                                   "#edf8e9",
                                   "#FF0000",
                                   "grey50"),
                    "SI10_BOTHER" = c("#6a51a3",
                                      "#9e9ac8",
                                      "#cbc9e2",
                                      "#f2f0f7",
                                      "#FF0000",
                                      "grey50")),
         SI10_Q1_Q8 = c("#08519c",
                        "#3182bd",
                        "#6baed6",
                        "#bdd7e7",
                        "#eff3ff",
                        "#FF0000",
                        "grey50"),
         SI10_Q9 = c("#d94701",
                     "#fd8d3c",
                     "#fdbe85",
                     "#feedde",
                     "#FF0000",
                     "grey50"),
         SI10_Q10 = c("#238b45",
                      "#74c476",
                      "#bae4b3",
                      "#edf8e9",
                      "#FF0000",
                      "grey50"),
         SI10_BOTHER = c("#6a51a3",
                         "#9e9ac8",
                         "#cbc9e2",
                         "#f2f0f7",
                         "#FF0000",
                         "grey50"))
}
